services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongo_db
    ports:
      - "27018:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
